//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoToEvents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliado
    {
        public Afiliado()
        {
            this.Evento = new HashSet<Evento>();
        }
    
        public int idAfiliado { get; set; }
        public string nombreAfiliado { get; set; }
        public string direccionAfiliado { get; set; }
        public string imgPathAfiliado { get; set; }
        public string emailAfiliado { get; set; }
        public string passwordAfiliado { get; set; }
        public string preguntaSeguridad { get; set; }
        public string respuestaSeguridad { get; set; }
        public bool statusAfiliado { get; set; }
        public System.DateTime fechaCreoAfiliado { get; set; }
        public System.DateTime fechaModiAfiliado { get; set; }
        public int idPais { get; set; }
        public int idCiudad { get; set; }
        public int idEstado { get; set; }
        public int raizVal { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Evento> Evento { get; set; }
    }
}
