//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoToEvents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.Puntuacion = new HashSet<Puntuacion>();
        }
    
        public int idEvento { get; set; }
        public int idAfiliado { get; set; }
        public string nombreAfiliado { get; set; }
        public int idCategoria { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaExpiracion { get; set; }
        public bool activo { get; set; }
        public string imgUrl { get; set; }
        public string direccion { get; set; }
        public string descripcion { get; set; }
        public decimal totalPuntaje { get; set; }
        public int cantPuntuaciones { get; set; }
        public int idCiudad { get; set; }
        public int idEstado { get; set; }
        public int idPais { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<Puntuacion> Puntuacion { get; set; }
    }
}
