//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoToEvents
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Promo2EventEntities : DbContext
    {
        public Promo2EventEntities()
            : base("name=Promo2EventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Afiliado> Afiliado { get; set; }
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<CategoriaAfiliado> CategoriaAfiliado { get; set; }
        public DbSet<Ciudad> Ciudad { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Evento> Evento { get; set; }
        public DbSet<Pais> Pais { get; set; }
        public DbSet<Puntuacion> Puntuacion { get; set; }
    }
}
