//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromoToEvents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntuacion
    {
        public int idPuntuacion { get; set; }
        public int valorPuntaje { get; set; }
        public System.DateTime fechaPuntaje { get; set; }
        public int idEvento { get; set; }
    
        public virtual Evento Evento { get; set; }
    }
}
